[prometheus]
host = '127.0.0.1'
port = 9090

[[chains]]
id = 'mantra-dukong-1'
grpc_addr = 'https://grpc.dukong.mantrachain.io'
[[chains.addresses]]
address = 'mantra1q8mgs55hfgkm7d5rret439997x87s2ekwcxlv0'
denom = 'uom'
display_denom = 'OM'
min_balance = '200000000000'
decimal_place = 6
role = 'test1'
refresh = '60s'
balance_url = 'https://www.mintscan.io/mantra-testnet/address/mantra1q8mgs55hfgkm7d5rret439997x87s2ekwcxlv0'
[[chains.addresses]]
address = 'mantra1ea4hlqfskjvn0ldenw8gv7jjdzrljcchm9vhhu'
denom = 'uom'
display_denom = 'OM'
min_balance = '1000000000000'
decimal_place = 6
role = 'test2'
refresh = '60s'
balance_url = 'https://www.mintscan.io/mantra-testnet/address/mantra1ea4hlqfskjvn0ldenw8gv7jjdzrljcchm9vhhu'

[[chains]]
id = '1'
evm_addr = 'https://eth.llamarpc.com'
[[chains.addresses]]
address = '0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B'
coin_type = "EVM"
denom = 'wei'
display_denom = 'ETH'
min_balance = '10000000000000000000'
decimal_place = 18
role = 'vitalik'
refresh = '300s'
balance_url = 'https://etherscan.io/address/0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B'